export const RULE_FIELDS: Array<{ id: string; label: string; kind: "text" | "list" | "number" | "date" | "bool" }> = [
  { id: "subject", label: "Тема", kind: "text" },
  { id: "subject_normalized", label: "Тема без Re/Fw", kind: "text" },
  { id: "from_email", label: "Адрес отправителя", kind: "text" },
  { id: "from_display_name", label: "Имя отправителя", kind: "text" },
  { id: "from_domain", label: "Домен отправителя", kind: "text" },
  { id: "from_tld", label: "Доменная зона", kind: "text" },
  { id: "to", label: "Получатели To", kind: "list" },
  { id: "cc", label: "Получатели Cc", kind: "list" },
  { id: "reply_to", label: "Reply-To", kind: "list" },
  { id: "message_id", label: "Message-ID", kind: "text" },
  { id: "received_at", label: "Дата получения", kind: "date" },
  { id: "sent_at", label: "Дата отправки", kind: "date" },
  { id: "size_bytes", label: "Размер, байт", kind: "number" },
  { id: "attachment_count", label: "Число вложений", kind: "number" },
  { id: "attachment_names", label: "Имена вложений", kind: "list" },
  { id: "attachment_extensions", label: "Расширения вложений", kind: "list" },
  { id: "body_full_text", label: "Полный текст", kind: "text" },
  { id: "body_new_text", label: "Новый текст без цитат", kind: "text" },
  { id: "body_preview", label: "Превью", kind: "text" },
  { id: "language", label: "Язык", kind: "text" },
  { id: "language_confidence", label: "Уверенность языка", kind: "number" },
  { id: "sentiment", label: "Тональность", kind: "text" },
  { id: "sentiment_score", label: "Балл тональности", kind: "number" },
  { id: "urgency_level", label: "Срочность", kind: "text" },
  { id: "urgency_score", label: "Балл срочности", kind: "number" },
  { id: "has_deadline", label: "Есть дедлайн", kind: "bool" },
  { id: "dates", label: "Даты", kind: "list" },
  { id: "deadlines", label: "Дедлайны", kind: "list" },
  { id: "earliest_deadline", label: "Ближайший дедлайн", kind: "date" },
  { id: "amounts", label: "Суммы", kind: "list" },
  { id: "currencies", label: "Валюты", kind: "list" },
  { id: "extracted_phones", label: "Телефоны", kind: "list" },
  { id: "extracted_emails", label: "Email из текста", kind: "list" },
  { id: "extracted_urls", label: "Ссылки", kind: "list" },
  { id: "url_domains", label: "Домены ссылок", kind: "list" },
  { id: "contract_numbers", label: "Номера договоров", kind: "list" },
  { id: "invoice_numbers", label: "Номера счетов", kind: "list" },
  { id: "act_numbers", label: "Номера актов", kind: "list" },
  { id: "ticket_ids", label: "Номера заявок", kind: "list" },
  { id: "inn_numbers", label: "ИНН", kind: "list" },
  { id: "kpp_numbers", label: "КПП", kind: "list" },
  { id: "ogrn_numbers", label: "ОГРН", kind: "list" },
  { id: "bank_account_candidates", label: "Расчётные счета", kind: "list" },
  { id: "has_attachments", label: "Есть вложения", kind: "bool" },
  { id: "url_domain_mismatch", label: "Домен ссылки отличается", kind: "bool" },
  { id: "header.auto-submitted", label: "Заголовок Auto-Submitted", kind: "text" },
  { id: "header.precedence", label: "Заголовок Precedence", kind: "text" },
  { id: "header.list-unsubscribe", label: "Заголовок List-Unsubscribe", kind: "text" },
  { id: "header.list-id", label: "Заголовок List-Id", kind: "text" },
  { id: "header.x-mailer", label: "Заголовок X-Mailer", kind: "text" },
  { id: "header.x-spam-flag", label: "Заголовок X-Spam-Flag", kind: "text" },
  { id: "header.x-spam-score", label: "Заголовок X-Spam-Score", kind: "text" },
];

export const OPERATORS: Array<{ id: string; label: string }> = [
  { id: "eq", label: "равно" },
  { id: "neq", label: "не равно" },
  { id: "contains", label: "содержит" },
  { id: "not_contains", label: "не содержит" },
  { id: "starts_with", label: "начинается с" },
  { id: "ends_with", label: "заканчивается на" },
  { id: "regex", label: "регулярное выражение" },
  { id: "in", label: "входит в список" },
  { id: "not_in", label: "не входит в список" },
  { id: "intersects", label: "пересекается со списком" },
  { id: "not_intersects", label: "не пересекается со списком" },
  { id: "exists", label: "существует" },
  { id: "not_exists", label: "не существует" },
  { id: "gt", label: "больше" },
  { id: "lt", label: "меньше" },
  { id: "before", label: "раньше" },
  { id: "after", label: "позже" },
  { id: "empty", label: "пусто" },
  { id: "not_empty", label: "не пусто" },
  { id: "full_text_match", label: "все слова" },
  { id: "phrase_match", label: "фраза" },
  { id: "always", label: "всегда" },
];
