import type { ProcessedMessage } from "@prisma/client";
import { emptyMessage, type NormalizedMessage } from "@/lib/mail/model";

export function storedMessage(row: ProcessedMessage): NormalizedMessage {
  const message = emptyMessage(row.receivedAt);
  return {
    ...message,
    subject: row.subject,
    subjectNormalized: row.subjectNormalized,
    fromEmail: row.fromEmail,
    fromDisplayName: row.fromDisplayName,
    fromDomain: row.fromDomain,
    fromTld: row.fromTld,
    to: row.toRecipients,
    cc: row.ccRecipients,
    replyTo: row.replyTo,
    messageId: row.messageIdHeader,
    sentAt: row.sentAt,
    sizeBytes: row.sizeBytes,
    attachmentCount: row.attachmentCount,
    attachmentNames: row.attachmentNames,
    attachmentExtensions: row.attachmentExtensions,
    hasAttachments: row.attachmentCount > 0,
    headers: (row.headersSnapshot as Record<string, string>) || {},
    bodyFullText: row.bodyFullText,
    bodyNewText: row.bodyNewText,
    bodyPreview: row.bodyPreview,
    bodyTruncated: row.bodyTruncated,
    bodyUnavailable: row.bodyUnavailable,
    bodyError: row.bodyError,
    quoteSplitConfidence: row.quoteSplitConfidence === "low" ? "low" : "high",
    language: row.language,
    languageConfidence: row.languageConfidence,
    sentiment: row.sentiment,
    sentimentScore: row.sentimentScore,
    urgencyLevel: row.urgencyLevel,
    urgencyScore: row.urgencyScore,
    phonesRaw: row.phonesRaw,
    phonesNormalized: row.phonesNormalized,
    emails: row.emails,
    urls: row.urls,
    urlDomains: row.urlDomains,
    urlDomainMismatch: row.urlDomainMismatch,
    dates: Array.isArray(row.dates) ? (row.dates as NormalizedMessage["dates"]) : [],
    deadlines: Array.isArray(row.deadlines) ? (row.deadlines as NormalizedMessage["deadlines"]) : [],
    earliestDeadline: row.earliestDeadline?.toISOString() ?? null,
    amounts: Array.isArray(row.amounts) ? (row.amounts as NormalizedMessage["amounts"]) : [],
    currencies: row.currencies,
    contractNumbers: row.contractNumbers,
    invoiceNumbers: row.invoiceNumbers,
    actNumbers: row.actNumbers,
    ticketIds: row.ticketIds,
    innNumbers: row.innNumbers,
    kppNumbers: row.kppNumbers,
    ogrnNumbers: row.ogrnNumbers,
    bankAccountCandidates: row.bankAccountCandidates,
    entityListsTruncated: row.entityListsTruncated,
  };
}
